# Form implementation generated from reading ui file '.\templates\about.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAbout(object):
    def setupUi(self, dlgAbout):
        dlgAbout.setObjectName("dlgAbout")
        dlgAbout.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        dlgAbout.resize(500, 400)
        dlgAbout.setMinimumSize(QtCore.QSize(500, 400))
        dlgAbout.setMaximumSize(QtCore.QSize(500, 400))
        dlgAbout.setModal(True)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=dlgAbout)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 30, 411, 341))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lblImagen = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.lblImagen.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.lblImagen.setText("")
        self.lblImagen.setPixmap(QtGui.QPixmap(".\\templates\\../img/empreaAbout.png"))
        self.lblImagen.setScaledContents(True)
        self.lblImagen.setObjectName("lblImagen")
        self.gridLayout.addWidget(self.lblImagen, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblVersion = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.lblVersion.setMinimumSize(QtCore.QSize(150, 25))
        self.lblVersion.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblVersion.setFont(font)
        self.lblVersion.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblVersion.setObjectName("lblVersion")
        self.horizontalLayout_2.addWidget(self.lblVersion)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCloseAbout = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.btnCloseAbout.setMinimumSize(QtCore.QSize(100, 25))
        self.btnCloseAbout.setMaximumSize(QtCore.QSize(100, 25))
        self.btnCloseAbout.setObjectName("btnCloseAbout")
        self.horizontalLayout.addWidget(self.btnCloseAbout)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblAutor = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.lblAutor.setMinimumSize(QtCore.QSize(250, 25))
        self.lblAutor.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblAutor.setFont(font)
        self.lblAutor.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblAutor.setObjectName("lblAutor")
        self.horizontalLayout_3.addWidget(self.lblAutor)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)

        self.retranslateUi(dlgAbout)
        QtCore.QMetaObject.connectSlotsByName(dlgAbout)

    def retranslateUi(self, dlgAbout):
        _translate = QtCore.QCoreApplication.translate
        dlgAbout.setWindowTitle(_translate("dlgAbout", "Dialog"))
        self.lblVersion.setText(_translate("dlgAbout", "Version 0.0.1"))
        self.btnCloseAbout.setText(_translate("dlgAbout", "Close"))
        self.lblAutor.setText(_translate("dlgAbout", "Autor: Nain López Álvarez ©"))
