# Form implementation generated from reading ui file '.\templates\about.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAbout(object):
    def setupUi(self, dlgAbout):
        dlgAbout.setObjectName("dlgAbout")
        dlgAbout.resize(500, 400)
        dlgAbout.setMinimumSize(QtCore.QSize(500, 400))
        dlgAbout.setMaximumSize(QtCore.QSize(500, 400))
        dlgAbout.setModal(True)
        self.btnCloseAbout = QtWidgets.QPushButton(parent=dlgAbout)
        self.btnCloseAbout.setGeometry(QtCore.QRect(200, 320, 100, 25))
        self.btnCloseAbout.setMinimumSize(QtCore.QSize(100, 25))
        self.btnCloseAbout.setMaximumSize(QtCore.QSize(100, 25))
        self.btnCloseAbout.setObjectName("btnCloseAbout")
        self.lbl = QtWidgets.QLabel(parent=dlgAbout)
        self.lbl.setGeometry(QtCore.QRect(210, 230, 50, 25))
        self.lbl.setMinimumSize(QtCore.QSize(50, 25))
        self.lbl.setMaximumSize(QtCore.QSize(50, 25))
        self.lbl.setObjectName("lbl")
        self.lblDniCif_2 = QtWidgets.QLabel(parent=dlgAbout)
        self.lblDniCif_2.setGeometry(QtCore.QRect(200, 270, 100, 25))
        self.lblDniCif_2.setMinimumSize(QtCore.QSize(100, 25))
        self.lblDniCif_2.setMaximumSize(QtCore.QSize(100, 25))
        self.lblDniCif_2.setObjectName("lblDniCif_2")
        self.lblImagen = QtWidgets.QLabel(parent=dlgAbout)
        self.lblImagen.setGeometry(QtCore.QRect(40, 30, 421, 131))
        self.lblImagen.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.lblImagen.setScaledContents(True)
        self.lblImagen.setObjectName("lblImagen")

        self.retranslateUi(dlgAbout)
        QtCore.QMetaObject.connectSlotsByName(dlgAbout)

    def retranslateUi(self, dlgAbout):
        _translate = QtCore.QCoreApplication.translate
        dlgAbout.setWindowTitle(_translate("dlgAbout", "Dialog"))
        self.btnCloseAbout.setText(_translate("dlgAbout", "Ok"))
        self.lbl.setText(_translate("dlgAbout", "algo"))
        self.lblDniCif_2.setText(_translate("dlgAbout", "v 00.000.00"))
        self.lblImagen.setText(_translate("dlgAbout", "IMagen"))
